---
name: auto_cancel_pipeline_on_job_failure
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/137815
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/433163
milestone: '16.7'
type: development
group: group::pipeline execution
default_enabled: false
