---
name: bulk_create_scan_result_policies
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/139163
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/435958
milestone: '16.8'
type: development
group: group::security policies
default_enabled: false
