---
name: cache_autocomplete_sources_labels
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/138226
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/433170
milestone: '16.7'
type: development
group: group::global search
default_enabled: true
