---
name: ci_parallel_remote_includes
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/136715
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/413770
milestone: '16.7'
type: development
group: group::pipeline authoring
default_enabled: true
