---
name: enforce_ssh_certificates_via_settings
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/136498
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/426235
milestone: '16.7'
type: development
group: group::source code
default_enabled: false
