---
name: environments_folder_new_look
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/137046
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/431928
milestone: '16.7'
type: development
group: group::environments
default_enabled: false
