---
name: github_import_increased_concurrent_workers
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/137832
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/432891
milestone: '16.7'
type: development
group: group::import and integrate
default_enabled: false
