---
name: optional_personal_namespace
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/137713
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/431978
milestone: '16.8'
type: development
group: group::tenant scale
default_enabled: false
