---
name: pause_clickhouse_workers_during_migration
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/138166
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/433389
milestone: '16.7'
type: development
group: group::runner
default_enabled: false
