---
name: service_accounts_crud
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/113884
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/397730
milestone: '15.11'
type: development
group: group::authentication
default_enabled: false
