---
name: ci_fix_input_types
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/434826
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/145257
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/443301
milestone: '16.10'
group: group::pipeline authoring
type: gitlab_com_derisk
default_enabled: false
