---
name: ci_partitioning_use_ci_stages_routing_table
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/440759
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/145902
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/443421
milestone: '16.10'
group: group::pipeline execution
type: gitlab_com_derisk
default_enabled: false
