---
name: ci_partitioning_use_ci_job_artifacts_routing_table
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/440760
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/144709
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/441759
milestone: '16.10'
group: group::pipeline execution
type: gitlab_com_derisk
default_enabled: false
