---
name: ci_text_interpolation
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/433002
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/142009
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/435177
milestone: '16.9'
group: group::pipeline authoring
type: gitlab_com_derisk
default_enabled: false
