---
name: external_pipeline_validation_migration
feature_issue_url: https://gitlab.com/gitlab-com/gl-infra/platform/runway/team/-/issues/135
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/142077
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/438627
milestone: '16.9'
group: group::scalability
type: gitlab_com_derisk
default_enabled: false
