---
name: group_labels_transfer
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/354890
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/146292
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/443874
milestone: '16.10'
group: group::project management
type: gitlab_com_derisk
default_enabled: false
