---
name: namespace_descendants_cache_expiration
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/433482
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/141588
rollout_issue_url: https://gitlab.com/gitlab-com/gl-infra/production/-/issues/17388
milestone: '16.8'
group: group::optimize
type: gitlab_com_derisk
default_enabled: false
