---
name: new_unassignment_service
feature_issue_url:
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/145726
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/443249
milestone: '16.10'
group: group::project management
type: gitlab_com_derisk
default_enabled: false
