---
name: rebuild_mv_drop_old_tables
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/431453
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/144478
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/441584
milestone: '16.10'
group: group::optimize
type: gitlab_com_derisk
default_enabled: false
