---
name: sync_audit_events_to_clickhouse
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/404405
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/140924
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/427738
milestone: '16.9'
group: group::compliance
type: gitlab_com_derisk
default_enabled: false
