---
name: use_partition_id_filter_on_ci_job_artifacts
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/430294
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/145522
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/444191
milestone: '16.10'
group: group::pipeline execution
type: gitlab_com_derisk
default_enabled: false
