---
name: web_ide_settings_sync
feature_issue_url: https://gitlab.com/gitlab-org/gitlab-web-ide/-/issues/282
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/146061
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/443652
milestone: '16.10'
group: group::ide
type: gitlab_com_derisk
default_enabled: false
