---
name: ai_duo_chat_switch
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/434802
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/140352
rollout_issue_url: https://gitlab.com/gitlab-com/gl-infra/production/-/issues/17301
milestone: '16.8'
group: group::ai framework
type: ops
default_enabled: true
